name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          debug: true
          script: |
            echo "Deploying to server"
            if [ ! -d "/astalife/blog-cms" ]; then
              git clone git@github.com-asta:AstaDK/blog-cms.git /astalife
            fi
            cd /astalife/blog-cms
            git pull origin main
            docker compose down
            docker compose -f docker-compose.prod.yml up -d --build
