name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SSH Key
        run: |
          echo "SSH Key (first 100 chars):"
          echo "${{ secrets.SERVER_SSH_KEY }}" | tr -d '\n' | cut -c1-100
          echo "Server Host:"
          echo "${{ secrets.SERVER_HOST }}"
          echo "Server User:"
          echo "${{ secrets.SERVER_USER }}"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "Deploying to server"
            if [ ! -d "blog-cms" ]; then
              git clone git@github.com-asta:AstaDK/blog-cms.git
            else
              cd blog-cms
              git pull origin main
            fi
            cd blog-cms
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml up -d
